{
  "hash": "65c488c021c95533d06ffef42af0a4d3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 3: Verify the Claim of Povery Change in Philadelphia\"\nsubtitle: \"Testing a published claim about neighborhood change against the data behind it\"\nauthor: \"Tatar Anurakwongsri\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-summary: \"Show code\"\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\nlibrary(sf)\nlibrary(ggplot2)\n```\n:::\n\n\n---\n\n## Part 1 — Reconstruct\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvars <- c(total_poverty = \"B17001_002\",\n               total_pop = \"B01003_001\",\n               median_income = \"B19013_001\"\n               )\n\ndata_2006 <- get_acs(\n  geography = \"tract\",\n  variables = vars,\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2010,\n  survey = \"acs5\",\n  geometry = TRUE,\n  output    = \"wide\"\n)\ndata_2006 <- data_2006 %>%\n  st_as_sf(coords = c(\"lon\", \"lat\"), crs = 4326)\n\ndata_2013 <- get_acs(\n  geography = \"tract\",\n  variables = vars,\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2017,\n  survey = \"acs5\",\n  geometry = TRUE,\n  output    = \"wide\"\n)\ndata_2013 <- data_2013 %>%\n  st_as_sf(coords = c(\"lon\", \"lat\"), crs = 4326)\n```\n:::\n\n\n### Notes from Article\n[Article link](https://whyy.org/articles/new-census-figures-on-philly-neighborhoods-show-inequality-high-numbers-of-whites-living-in-poverty/)\n\n- Fairhill 61% poverty rate\n- 12% --> 26% poverty rate in Eastwick \n- 2% --> 19% poverty rate in Holmesburg \n- Median household income of Tioga-Nicetown plummeted from 28,026 to 17,493\n\n### Variables of Interest\n\n- Poverty rate (total)\n- Median household income\n\n### Variable Codes\n- total_poverty: B17001_002\n- total_pop: B01003_001\n- median_income: B19013_001\n\n\nThe article claims a 14% increase in poverty rate between the 2006-2010 and\n2013-2017 ACS data in the neighborhood of Eastwick, a 17% increase in poverty rate\nin Holmesburg, a drop in median household income in Tioga-Nicetown, and a 61% poverty\nrate in Fairhill.\n\nThe article pointed variables of interest from the census tract: total poverty \nrate, white poverty rate, median household income, and white population. Data from\nthe 5-year ACS (2006-2010 & 2013-2017) and 2016 1-year ACS were used. The article\nstates using these data tables while referencing the 2016-2017 ACS as the then-newest\ncensus data. I assumed some of the time period for some of the claims: Fairhill, Holmesburg,\nTioga-Nicetown and the income gap. No years were specified for these so I assumed\n2013-2017 based on the title. The time periods that overlap are 2013-2017 and\n2016-2017. However, the 1-year ACS data is not available at the tract level due\nto the area 65,000 population requirement. The Census Bureau does not recommend\ncomparing different time-period lengths as they measure characteristics of the\npopulation in different ways. \n\n\n### Load Neighborhood Data\n\n::: {.cell}\n\n```{.r .cell-code}\ngithub_path <- \"https://raw.githubusercontent.com/opendataphilly/odp-data-storage/5c4538b5f4d2a26a81b7fab2d0006d327a39e3d0/philadelphia-neighborhoods/philadelphia-neighborhoods.geojson\"\n\nneighborhoods <- st_read(github_path)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `philadelphia-neighborhoods' from data source \n  `https://raw.githubusercontent.com/opendataphilly/odp-data-storage/5c4538b5f4d2a26a81b7fab2d0006d327a39e3d0/philadelphia-neighborhoods/philadelphia-neighborhoods.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 159 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -75.28026 ymin: 39.86701 xmax: -74.95576 ymax: 40.13799\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nneighborhoods <- st_make_valid(neighborhoods) # Fix broken geometry of neighborhoods\n\nneighborhoods_2006 <- data_2006 %>%\n  st_as_sf(coords = c(\"lon\", \"lat\"), crs = 4326) %>%\n  st_transform(st_crs(neighborhoods)) %>%\n  st_join(neighborhoods) %>%\n  st_drop_geometry()\n\nneighborhoods_2013 <- data_2013 %>%\n  st_as_sf(coords = c(\"lon\", \"lat\"), crs = 4326) %>%\n  st_transform(st_crs(neighborhoods)) %>%\n  st_join(neighborhoods) %>%\n  st_drop_geometry()\n```\n:::\n\n\nI used a new method from the sf package called st_make_valid to fix the geometry error during data import.\n\n\n### Aggregate Data by Neighborhood\n\n::: {.cell}\n\n```{.r .cell-code}\ngrouped_neighborhoods_2006 <- neighborhoods_2006 %>%\n  group_by(LISTNAME) %>%\n  summarise(\n    total_pop = sum(total_popE, na.rm = TRUE),\n    total_pop_moe = moe_sum(moe = total_popM, estimate = total_popE, na.rm = TRUE),\n    \n    total_poverty = sum(total_povertyE, na.rm = TRUE),\n    total_poverty_moe = moe_sum(moe = total_povertyM, estimate = total_povertyE, na.rm = TRUE),\n    \n    median_income = sum(median_incomeE, na.rm = TRUE),\n    median_income_moe = moe_sum(moe = median_incomeM, estimate = median_incomeE, na.rm = TRUE)\n  )\n\ngrouped_neighborhoods_2013 <- neighborhoods_2013 %>%\n  group_by(LISTNAME) %>%\n  summarise(\n    total_pop = sum(total_popE, na.rm = TRUE),\n    total_pop_moe = moe_sum(moe = total_popM, estimate = total_popE, na.rm = TRUE),\n    \n    total_poverty = sum(total_povertyE, na.rm = TRUE),\n    total_poverty_moe = moe_sum(moe = total_povertyM, estimate = total_povertyE, na.rm = TRUE),\n    \n    median_income = sum(median_incomeE, na.rm = TRUE),\n    median_income_moe = moe_sum(moe = median_incomeM, estimate = median_incomeE, na.rm = TRUE)\n  )\n```\n:::\n\n\nThe aggregation of neighborhoods worked perfectly fine. The only data irregularities\nare found in the airport area for the 5-year ACS, which yielded little to no estimates.\nOn the other hand, the northeast philadelphia airport reported statistics. However, \nthis is likely due to the lack of residents living in the immediate proximity of the \nairport (assuming this is the international airport). Interestingly, the 2016\n1-year ACS has data estimates for the airport neighborhood.\n\n## Part 2: Test\n\n### Calculate Poverty Rate\n\n::: {.cell}\n\n```{.r .cell-code}\ngrouped_neighborhoods_2006 <- grouped_neighborhoods_2006 %>%\n  mutate(pov_rate = (total_poverty / total_pop) * 100,\n         pov_rate_moe = moe_prop(total_poverty, total_pop, total_poverty_moe, total_pop_moe),\n         pov_moe_pct = (pov_rate_moe / pov_rate) * 100) %>%\n  mutate(reliability = case_when(\n  pov_moe_pct < 12  ~ \"High\",\n  pov_moe_pct < 40 ~ \"Moderate\",\n  TRUE         ~ \"Low\"\n  ))\n  \ngrouped_neighborhoods_2013 <- grouped_neighborhoods_2013 %>%\n  mutate(pov_rate = (total_poverty / total_pop) * 100,\n         pov_rate_moe = moe_prop(total_poverty, total_pop, total_poverty_moe, total_pop_moe),\n         pov_moe_pct = (pov_rate_moe / pov_rate) * 100) %>%\n  mutate(reliability = case_when(\n  pov_moe_pct < 12  ~ \"High\",\n  pov_moe_pct < 40 ~ \"Moderate\",\n  TRUE         ~ \"Low\"\n  ))\n```\n:::\n\n\n### View Reliability of Each Neighborhood as a Data Table \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gt)\n\nreliability_table <- grouped_neighborhoods_2006 %>%\n  mutate(\n    dot = case_when(\n      pov_moe_pct < 12  ~ \"🟢\",\n      pov_moe_pct <= 40 ~ \"🟡\",\n      TRUE              ~ \"🔴\"\n    ),\n    flag = case_when(\n      pov_moe_pct < 12  ~ \"Reliable\",\n      pov_moe_pct <= 40 ~ \"Somewhat reliable\",\n      TRUE              ~ \"Unreliable\"\n    ),\n  ) %>%\n  arrange(desc(pov_moe_pct)) %>%\n  select(dot, LISTNAME, pov_rate, pov_rate_moe, pov_moe_pct, flag)\n\nreliability_table %>%\n  gt() %>%\n  fmt_number(columns = c(pov_rate, pov_rate_moe), decimals = 0) %>%\n  fmt_number(columns = pov_moe_pct, decimals = 1) %>%\n  cols_label(\n    dot               = \"\",\n    LISTNAME          = \"Neighborhood\",\n    pov_rate          = \"Poverty Rate\",\n    pov_rate_moe      = \"MOE\",\n    pov_moe_pct       = \"CV (%)\",\n    flag              = \"Reliability\"\n  ) %>%\n  cols_align(align = \"center\", columns = dot) %>%\n  tab_header(\n    title    = \"Population below 100% of the poverty level\",\n    subtitle = \"Philadelphia Neighborhoods, ACS 2006-2010 5-year estimates\"\n  ) %>%\n  tab_source_note(\n    \"Reliability thresholds follow Jurjevich et al. (2018): CV < 12% reliable, 12–40% somewhat reliable, > 40% unreliable.\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uhjqsagbqu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uhjqsagbqu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uhjqsagbqu thead, #uhjqsagbqu tbody, #uhjqsagbqu tfoot, #uhjqsagbqu tr, #uhjqsagbqu td, #uhjqsagbqu th {\n  border-style: none;\n}\n\n#uhjqsagbqu p {\n  margin: 0;\n  padding: 0;\n}\n\n#uhjqsagbqu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uhjqsagbqu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uhjqsagbqu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uhjqsagbqu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uhjqsagbqu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uhjqsagbqu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uhjqsagbqu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uhjqsagbqu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uhjqsagbqu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uhjqsagbqu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uhjqsagbqu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uhjqsagbqu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uhjqsagbqu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uhjqsagbqu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uhjqsagbqu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uhjqsagbqu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uhjqsagbqu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uhjqsagbqu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uhjqsagbqu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uhjqsagbqu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uhjqsagbqu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uhjqsagbqu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uhjqsagbqu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uhjqsagbqu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uhjqsagbqu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uhjqsagbqu .gt_left {\n  text-align: left;\n}\n\n#uhjqsagbqu .gt_center {\n  text-align: center;\n}\n\n#uhjqsagbqu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uhjqsagbqu .gt_font_normal {\n  font-weight: normal;\n}\n\n#uhjqsagbqu .gt_font_bold {\n  font-weight: bold;\n}\n\n#uhjqsagbqu .gt_font_italic {\n  font-style: italic;\n}\n\n#uhjqsagbqu .gt_super {\n  font-size: 65%;\n}\n\n#uhjqsagbqu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uhjqsagbqu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uhjqsagbqu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uhjqsagbqu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uhjqsagbqu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uhjqsagbqu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uhjqsagbqu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uhjqsagbqu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uhjqsagbqu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal\" style>Population below 100% of the poverty level</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Philadelphia Neighborhoods, ACS 2006-2010 5-year estimates</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dot\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"LISTNAME\">Neighborhood</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pov_rate\">Poverty Rate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pov_rate_moe\">MOE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pov_moe_pct\">CV (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"flag\">Reliability</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wissahickon Hills</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">3</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.9</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mechanicsville</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.6</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Penrose</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.6</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Blue Bell Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Pennypack Woods</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Andorra</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">6</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Dearnley Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">10</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Navy Yard</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">16</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Packer Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">16</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Winchester Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Aston-Woodbridge</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Normandy Village</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">11</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Franklin Mills</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Millbrook</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Eastwick</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Torresdale</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Chinatown</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">17</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Chestnut Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wissahickon</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">15</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germany Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Roxborough Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Crestmont Farms</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Academy Gardens</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Byberry</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Cedarbrook</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mount Airy, West</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">11</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Port Richmond</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">21</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Lexington Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Parkwood Manor</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Burholme</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">10</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Poplar</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">32</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Northeast Phila Airport</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Upper Roxborough</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Clearview</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">21</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Greenwich</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">30</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Callowhill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">22</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Morrell Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Manayunk</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">14</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Melrose Park Gardens</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">16</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Pennsport</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">24</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Modena</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Ludlow</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">40</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Society Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Torresdale</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fox Chase</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">10</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Garden Court</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">24</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wissahickon Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Pennypack</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">11</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Roxborough</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Northern Liberties</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">22</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Summerdale</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">26</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Bridesburg</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">24</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Yorktown</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fitler Square</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">11</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Poplar</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">33</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Whitman</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Riverfront</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">15</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Queen Village</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">17</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Old City</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">14</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Bella Vista</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">18</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Lower Moyamensing</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Stadium District</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">17</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Hawthorne</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">19</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Nicetown</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">30</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Oak Lane</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">16</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, Westside</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">26</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Holmesburg</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">14</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wynnefield Heights</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Passyunk</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">27</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Rhawnhurst</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">14</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, Penn Knox</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, West Central</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">21</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, Morton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">24</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Somerton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">10</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fern Rock</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">21</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Cedar Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">24</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Tacony</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">16</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Powelton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mount Airy, East</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">13</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Pennypack Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">13</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Parkside</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">40</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Dickinson Narrows</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">26</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Crescentville</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">21</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Parkside</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">30</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Kensington, Old</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">36</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Woodland Terrace</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, East</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Dunlap</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">35</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Elmwood</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">25</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Haverford North</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">McGuire</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">60</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Industrial</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">30</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Ogontz</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">22</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, Southwest</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">27</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Oak Lane</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">14</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Spring Garden</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wister</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">32</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Bustleton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">11</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Carroll Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">35</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Falls</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Belmont</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Graduate Hospital</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">19</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Spruce Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fairmount</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Washington Square West</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">18</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Girard Estates</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">22</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Passyunk Square</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">26</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Lawndale</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">18</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Sharswood</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">37</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Walnut Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">33</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Glenwood</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">38</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Newbold</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">24</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Passyunk</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">30</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Bartram Village</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wynnefield</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">25</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Francisville</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">36</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Point Breeze</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">28</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Rittenhouse</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">16</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Center City East</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">13</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Grays Ferry</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fishtown - Lower Kensington</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">25</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Paschall</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">28</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Oxford Circle</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">19</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Allegheny West</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mill Creek</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">37</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Northwood</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Southwest Schuylkill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">27</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Overbrook</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">24</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mantua</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">40</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wissinoming</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">24</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Powelton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Kingsessing</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">30</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mayfair</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">20</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Tioga</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">32</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Logan</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">28</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Cobbs Creek</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Olney</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">26</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Frankford</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">32</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">University City</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">28</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Kensington</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">41</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Haddington</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">33</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Hunting Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Feltonville</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">36</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Brewerytown</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">54</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Franklinville</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">46</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Juniata Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">41</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Logan Square</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">19</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Stanton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">47</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Richmond</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">37</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Strawberry Mansion</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">43</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Hartranft</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">47</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Kensington, West</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">53</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fairhill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">54</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Harrowgate</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">44</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">North Central</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">49</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Upper Kensington</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">55</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Airport</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">NaN</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">NaN</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">NaN</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Unreliable</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"6\">Reliability thresholds follow Jurjevich et al. (2018): CV &lt; 12% reliable, 12–40% somewhat reliable, &gt; 40% unreliable.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreliability_table <- grouped_neighborhoods_2013 %>%\n  mutate(\n    dot = case_when(\n      pov_moe_pct < 12  ~ \"🟢\",\n      pov_moe_pct <= 40 ~ \"🟡\",\n      TRUE              ~ \"🔴\"\n    ),\n    flag = case_when(\n      pov_moe_pct < 12  ~ \"Reliable\",\n      pov_moe_pct <= 40 ~ \"Somewhat reliable\",\n      TRUE              ~ \"Unreliable\"\n    ),\n  ) %>%\n  arrange(desc(pov_moe_pct)) %>%\n  select(dot, LISTNAME, pov_rate, pov_rate_moe, pov_moe_pct, flag)\n\nreliability_table %>%\n  gt() %>%\n  fmt_number(columns = c(pov_rate, pov_rate_moe), decimals = 0) %>%\n  fmt_number(columns = pov_moe_pct, decimals = 1) %>%\n  cols_label(\n    dot               = \"\",\n    LISTNAME          = \"Neighborhood\",\n    pov_rate          = \"Poverty Rate\",\n    pov_rate_moe      = \"MOE\",\n    pov_moe_pct       = \"CV (%)\",\n    flag              = \"Reliability\"\n  ) %>%\n  cols_align(align = \"center\", columns = dot) %>%\n  tab_header(\n    title    = \"Population below 100% of the poverty level\",\n    subtitle = \"Philadelphia Neighborhoods, ACS 2006-2010 5-year estimates\"\n  ) %>%\n  tab_source_note(\n    \"Reliability thresholds follow Jurjevich et al. (2018): CV < 12% reliable, 12–40% somewhat reliable, > 40% unreliable.\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wcxqauecew\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wcxqauecew table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wcxqauecew thead, #wcxqauecew tbody, #wcxqauecew tfoot, #wcxqauecew tr, #wcxqauecew td, #wcxqauecew th {\n  border-style: none;\n}\n\n#wcxqauecew p {\n  margin: 0;\n  padding: 0;\n}\n\n#wcxqauecew .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wcxqauecew .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wcxqauecew .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wcxqauecew .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wcxqauecew .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wcxqauecew .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wcxqauecew .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wcxqauecew .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wcxqauecew .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wcxqauecew .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wcxqauecew .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wcxqauecew .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wcxqauecew .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wcxqauecew .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wcxqauecew .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wcxqauecew .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wcxqauecew .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wcxqauecew .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wcxqauecew .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wcxqauecew .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wcxqauecew .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wcxqauecew .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wcxqauecew .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wcxqauecew .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wcxqauecew .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wcxqauecew .gt_left {\n  text-align: left;\n}\n\n#wcxqauecew .gt_center {\n  text-align: center;\n}\n\n#wcxqauecew .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wcxqauecew .gt_font_normal {\n  font-weight: normal;\n}\n\n#wcxqauecew .gt_font_bold {\n  font-weight: bold;\n}\n\n#wcxqauecew .gt_font_italic {\n  font-style: italic;\n}\n\n#wcxqauecew .gt_super {\n  font-size: 65%;\n}\n\n#wcxqauecew .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wcxqauecew .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wcxqauecew .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wcxqauecew .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wcxqauecew .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wcxqauecew .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wcxqauecew .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wcxqauecew .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wcxqauecew div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal\" style>Population below 100% of the poverty level</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Philadelphia Neighborhoods, ACS 2006-2010 5-year estimates</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dot\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"LISTNAME\">Neighborhood</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pov_rate\">Poverty Rate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pov_rate_moe\">MOE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pov_moe_pct\">CV (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"flag\">Reliability</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mechanicsville</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">6</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.7</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Navy Yard</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">2</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.6</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Packer Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">2</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.6</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wissahickon Hills</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Franklin Mills</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Millbrook</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Andorra</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Pennypack Woods</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Crestmont Farms</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">6</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Winchester Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germany Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">10</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Roxborough Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">10</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Normandy Village</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">15</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Penrose</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">32</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Dearnley Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">16</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Aston-Woodbridge</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">10</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Torresdale</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Blue Bell Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">14</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Lexington Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">16</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Burholme</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">18</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Cedarbrook</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wissahickon</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">18</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Byberry</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Port Richmond</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">20</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Pennsport</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">18</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Upper Roxborough</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">10</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Callowhill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">21</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Academy Gardens</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Yorktown</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">28</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Chestnut Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">6</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Poplar</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">35</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Eastwick</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">26</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Parkwood Manor</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Chinatown</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">36</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">14</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Queen Village</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Greenwich</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Torresdale</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Riverfront</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">11</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Morrell Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">7</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mount Airy, West</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Ludlow</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">35</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Stadium District</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">16</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Modena</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">8</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Passyunk</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">21</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Northeast Phila Airport</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Bella Vista</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">10</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Passyunk Square</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">13</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Manayunk</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">18</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Poplar</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">34</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Society Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">10</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Clearview</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">30</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, West Central</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Bridesburg</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">15</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Summerdale</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">26</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Holmesburg</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">18</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fitler Square</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">9</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Garden Court</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">26</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Whitman</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">26</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Tacony</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">22</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Carroll Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">34</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Lower Moyamensing</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">26</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Roxborough</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">13</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Dickinson Narrows</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">22</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fox Chase</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">15</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wissahickon Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">11</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, Morton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mount Airy, East</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">14</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Dunlap</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">37</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Pennypack</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">13</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Parkside</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">38</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Northern Liberties</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">21</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Oak Lane</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">19</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Nicetown</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">40</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Hawthorne</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fishtown - Lower Kensington</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">19</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Center City East</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">18</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fairmount</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">17</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.2</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Kensington, Old</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">28</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Spring Garden</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">17</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Francisville</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">28</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wynnefield Heights</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Melrose Park Gardens</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">25</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Girard Estates</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">18</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Logan Square</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">15</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fern Rock</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">25</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Cedar Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">25</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Industrial</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">28</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Sharswood</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">32</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Point Breeze</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">20</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Parkside</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">33</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Old City</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">15</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Somerton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, Westside</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Crescentville</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Newbold</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">21</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Falls</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">22</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Passyunk</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">28</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Northwood</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wynnefield</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Elmwood</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">32</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Pennypack Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Brewerytown</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">41</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Allegheny West</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Rhawnhurst</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">19</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Graduate Hospital</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Walnut Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">34</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Grays Ferry</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">25</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, Penn Knox</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">44</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Woodland Terrace</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">27</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Bustleton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">13</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Belmont</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">40</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Glenwood</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, Southwest</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">37</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">McGuire</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">61</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Spruce Hill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">25</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Oak Lane</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">20</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Overbrook</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">24</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Powelton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wissinoming</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">24</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Washington Square West</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">14</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Haverford North</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">41</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Kingsessing</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Paschall</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">33</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Rittenhouse</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">12</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Ogontz</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Lawndale</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Bartram Village</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">33</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mill Creek</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Cobbs Creek</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Southwest Schuylkill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Wister</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">37</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">East Kensington</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">37</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Frankford</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">34</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Germantown, East</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">30</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Juniata Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Richmond</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">31</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Logan</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">34</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Haddington</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">32</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mayfair</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Tioga</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">36</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Harrowgate</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">39</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Oxford Circle</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Mantua</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">40</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Olney</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">29</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">West Powelton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">37</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">North Central</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">42</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Feltonville</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">38</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Strawberry Mansion</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">43</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">University City</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">23</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Franklinville</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">51</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Stanton</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">45</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Hunting Park</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">43</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Hartranft</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">43</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Fairhill</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">57</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Upper Kensington</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">56</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Kensington, West</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">50</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"LISTNAME\" class=\"gt_row gt_left\">Airport</td>\n<td headers=\"pov_rate\" class=\"gt_row gt_right\">NaN</td>\n<td headers=\"pov_rate_moe\" class=\"gt_row gt_right\">NaN</td>\n<td headers=\"pov_moe_pct\" class=\"gt_row gt_right\">NaN</td>\n<td headers=\"flag\" class=\"gt_row gt_left\">Unreliable</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"6\">Reliability thresholds follow Jurjevich et al. (2018): CV &lt; 12% reliable, 12–40% somewhat reliable, &gt; 40% unreliable.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n### Calculate change between two time periods and margin of error of this change\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_2006 <- select(grouped_neighborhoods_2006, \n                        c(LISTNAME, pov_rate_2006 = pov_rate, pov_moe_2006 = pov_rate_moe,\n                          median_income_2006 = median_income, income_moe_2006 = median_income_moe))\nselected_2013 <- select(grouped_neighborhoods_2013,\n                        c(LISTNAME, pov_rate_2013 = pov_rate, pov_moe_2013 = pov_rate_moe,\n                          median_income_2013 = median_income, income_moe_2013 = median_income_moe))\n\ncomparison_df <- inner_join(selected_2006,selected_2013, by = \"LISTNAME\") %>%\n  na.omit(comparison_df)\n\npov_comparison <- comparison_df %>%\n  mutate(\n    pov_change = pov_rate_2013 - pov_rate_2006,\n    se_1     = pov_moe_2013 / 1.645,\n    se_2     = pov_moe_2006 / 1.645,\n    se_diff  = sqrt(se_1^2 + se_2^2),\n    moe_diff = se_diff * 1.645,\n    z        = pov_change / se_diff,\n    significant = abs(z) > 1.645\n  )\n\nincome_comparison <- comparison_df %>%\n  mutate(\n    income_change = median_income_2013 - median_income_2006,\n    se_1     = income_moe_2013 / 1.645,\n    se_2     = income_moe_2006 / 1.645,\n    se_diff  = sqrt(se_1^2 + se_2^2),\n    moe_diff = se_diff * 1.645,\n    z        = income_change / se_diff,\n    significant = abs(z) > 1.645\n  )\n\npov_comparison %>%\n  count(significant)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  significant     n\n  <lgl>       <int>\n1 TRUE          158\n```\n\n\n:::\n:::\n\n\n\n### View Biggest Percent Changes\n\n::: {.cell}\n\n```{.r .cell-code}\npov_comparison %>%\n  filter(significant) %>%\n  ggplot(aes(x = reorder(LISTNAME, pov_change), y = pov_change)) +\n  geom_col(aes(fill = pov_change > 0)) +\n  geom_errorbar(aes(ymin = pov_change - moe_diff,\n                    ymax = pov_change + moe_diff), width = 0.3) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  coord_flip() +\n  theme_minimal() +\n  labs(title = \"Statistically significant change in poverty count\",\n       subtitle = \"2006–2010 vs 2013–2017, ACS 5-year estimates\",\n       x = \"Neighborhoods\", y = \"Change in people below poverty level (%)\")\n```\n\n::: {.cell-output-display}\n![](assignment3_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\nAll neighborhoods that had data were highly reliable. The only unreliable\nneighborhood was the airport, which didn't have any data in the first place. Out \nof the 159 neighborhoods, all 159 had statistically significant changes to their\npoverty rate. East Park, Navy Yard, Brewerytown, and Packer Park experienced the \nbiggest decrease in poverty rate, while Penrose and Chinatown saw the greatest \nrise in poverty rate.\n\nThe only neighborhood that produce NAs was the airport, because its population and poverty\ncolumns were 0 due to no one living there. Division with 0 will produce NAs as it \nis not possible. Because it was the only neighborhood that had an NA, I removed it \nfrom the comparison data frame. If there had been more neighborhoods with NAs, I would\nexplore ACS data sets from other years to find more complete data.\n\n\n## Part 3: Adjudicate\n\n### Poverty-Related Claims\n\n::: {.cell}\n\n```{.r .cell-code}\npov_comparison %>%\n  filter(LISTNAME == 'Eastwick')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 16\n  LISTNAME pov_rate_2006 pov_moe_2006 median_income_2006 income_moe_2006\n  <chr>            <dbl>        <dbl>              <dbl>           <dbl>\n1 Eastwick          11.8       0.0440             245827          29535.\n# ℹ 11 more variables: pov_rate_2013 <dbl>, pov_moe_2013 <dbl>,\n#   median_income_2013 <dbl>, income_moe_2013 <dbl>, pov_change <dbl>,\n#   se_1 <dbl>, se_2 <dbl>, se_diff <dbl>, moe_diff <dbl>, z <dbl>,\n#   significant <lgl>\n```\n\n\n:::\n\n```{.r .cell-code}\npov_comparison %>%\n  filter(LISTNAME == 'Holmesburg')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 16\n  LISTNAME   pov_rate_2006 pov_moe_2006 median_income_2006 income_moe_2006\n  <chr>              <dbl>        <dbl>              <dbl>           <dbl>\n1 Holmesburg          14.3       0.0247             397548          28031.\n# ℹ 11 more variables: pov_rate_2013 <dbl>, pov_moe_2013 <dbl>,\n#   median_income_2013 <dbl>, income_moe_2013 <dbl>, pov_change <dbl>,\n#   se_1 <dbl>, se_2 <dbl>, se_diff <dbl>, moe_diff <dbl>, z <dbl>,\n#   significant <lgl>\n```\n\n\n:::\n\n```{.r .cell-code}\npov_comparison %>%\n  filter(LISTNAME == 'Fairhill')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 16\n  LISTNAME pov_rate_2006 pov_moe_2006 median_income_2006 income_moe_2006\n  <chr>            <dbl>        <dbl>              <dbl>           <dbl>\n1 Fairhill          53.6       0.0381             129856          14306.\n# ℹ 11 more variables: pov_rate_2013 <dbl>, pov_moe_2013 <dbl>,\n#   median_income_2013 <dbl>, income_moe_2013 <dbl>, pov_change <dbl>,\n#   se_1 <dbl>, se_2 <dbl>, se_diff <dbl>, moe_diff <dbl>, z <dbl>,\n#   significant <lgl>\n```\n\n\n:::\n:::\n\n\n### Income-related claims\n\n::: {.cell}\n\n```{.r .cell-code}\nincome_comparison %>%\n  filter(LISTNAME %in% c(\"Tioga\", \"Nicetown\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 16\n  LISTNAME pov_rate_2006 pov_moe_2006 median_income_2006 income_moe_2006\n  <chr>            <dbl>        <dbl>              <dbl>           <dbl>\n1 Nicetown          30.0       0.0542              99815           9568.\n2 Tioga             32.1       0.0334             307688          29974.\n# ℹ 11 more variables: pov_rate_2013 <dbl>, pov_moe_2013 <dbl>,\n#   median_income_2013 <dbl>, income_moe_2013 <dbl>, income_change <dbl>,\n#   se_1 <dbl>, se_2 <dbl>, se_diff <dbl>, moe_diff <dbl>, z <dbl>,\n#   significant <lgl>\n```\n\n\n:::\n:::\n\n\n1. Claims that are supported\n\nThe poverty rate in Eastwick did indeed increased from 12% to 26% between the\n2006-2010 and 2013-2017 ACS. The high reliability also indicates this statistic\nis trustworthy. \n\n2. Claims that are unsupported\n\nFairhill did not have a 61% poverty rate in either ACS data sets, as the\npoverty rate hovered around 55%. The Holmesburg claim is completely wrong. The\npoverty rate was never 2% and never reach the 19% as the article suggests. Its\npoverty rate was 14% in 2006-2010 and increased significantly to ~18% in\n2013-2017. Lastly, the median income of Nicetown decreased significantly, but did \nnot match the figures the article suggested. In 2006-2010, the median household\nincome of Nicetown was 99,815, decreasing to 72,443 by the time of the next\n5-year ACS. Tioga had a median household income of 307,688 in 2006-2010, declining \nto 296,165 by 2013-2017, which was an insignificant decrease.\n\n## Part 4: Rewrite\n\nBetween the 2006-2010 and 2013-2017 ACS data sets, the Eastwick neighborhood\nexperienced a poverty rate increase from 12% to 26%, which was statistically\nsignificant. Holemesburg saw a 4% increase in its poverty rate, which was significant\nin the neighborhood's context. Fairhill had a high, but consistent poverty rate\nof 55% across the two ACS time spans. Lastly, both Tioga and Nicetown experienced\na decrease in median income: 307,688 to 296,165 for the former and 99,815 to 72,443\nfor the latter. Due to the high median income in Tioga, this was not a significant\nchange. However, the decrease in income was significant for Nicetown.\n\n",
    "supporting": [
      "assignment3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}